import nodemailer from 'nodemailer'
import { prisma } from './prisma.js'
import { decryptOptional } from './crypto.js'

async function getTransport() {
  const config = await prisma.smtpConfig.findFirst({ where: { enabled: true } })
  if (!config) return null
  return nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: { user: config.user, pass: decryptOptional(config.password) },
  })
}

async function getFrom() {
  const config = await prisma.smtpConfig.findFirst({ where: { enabled: true } })
  if (!config) return null
  return `"${config.fromName}" <${config.fromEmail}>`
}

export async function sendInviteEmail(to: string, babyName: string, inviterName: string, inviteUrl: string) {
  const transport = await getTransport()
  if (!transport) return
  await transport.sendMail({
    from: await getFrom() ?? undefined,
    to,
    subject: `${inviterName} invited you to track ${babyName} on Babything`,
    html: `
      <p>Hi there,</p>
      <p><strong>${inviterName}</strong> has invited you to help track <strong>${babyName}</strong> on Babything.</p>
      <p><a href="${inviteUrl}" style="background:#ef5144;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;display:inline-block;margin:16px 0;">Accept invite</a></p>
      <p>This link expires in 7 days.</p>
    `,
  })
}

export async function sendPasswordResetEmail(to: string, name: string, resetUrl: string) {
  const transport = await getTransport()
  if (!transport) return
  await transport.sendMail({
    from: await getFrom() ?? undefined,
    to,
    subject: 'Reset your Babything password',
    html: `
      <p>Hi ${name},</p>
      <p>You requested a password reset for your Babything account.</p>
      <p><a href="${resetUrl}" style="background:#ef5144;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;display:inline-block;margin:16px 0;">Reset password</a></p>
      <p>This link expires in 1 hour. If you didn't request this, ignore this email.</p>
    `,
  })
}

export async function sendReportEmail(to: string, babyName: string, pdfBuffer: Buffer, filename: string) {
  const transport = await getTransport()
  if (!transport) throw new Error('SMTP not configured')
  await transport.sendMail({
    from: await getFrom() ?? undefined,
    to,
    subject: `Pediatric Report for ${babyName}`,
    html: `
      <p>Hi,</p>
      <p>Please find attached the pediatric report for <strong>${babyName}</strong>, generated by Babything.</p>
      <p style="color:#78716c;font-size:12px;">This report was generated at your request and contains health tracking data.</p>
    `,
    attachments: [{
      filename,
      content: pdfBuffer,
      contentType: 'application/pdf',
    }],
  })
}

export async function sendTestEmail(to: string) {
  const transport = await getTransport()
  if (!transport) throw new Error('SMTP not configured')
  await transport.verify()
  await transport.sendMail({
    from: await getFrom() ?? undefined,
    to,
    subject: 'Babything — SMTP test',
    text: 'SMTP is configured correctly.',
  })
}
