import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
export default function LandingPage() {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "min-h-screen", children: [_jsx("header", { className: "bg-white border-b border-stone-100", children: _jsxs("div", { className: "max-w-5xl mx-auto px-6 py-4 flex items-center justify-between", children: [_jsx("h1", { className: "text-xl font-bold text-brand-600", children: "Babything" }), _jsx("button", { onClick: () => navigate('/signup'), className: "btn-primary text-sm", children: "Start free trial" })] }) }), _jsxs("main", { className: "max-w-5xl mx-auto px-6 py-16 space-y-16", children: [_jsxs("section", { className: "text-center space-y-6", children: [_jsx("h2", { className: "text-4xl font-bold text-stone-800", children: "Track everything about your baby." }), _jsx("p", { className: "text-lg text-stone-500 max-w-2xl mx-auto", children: "Feedings, diapers, sleep, growth, vaccines, medications, and milestones \u2014 all in one place. Share with caregivers in real time." }), _jsx("button", { onClick: () => navigate('/signup'), className: "btn-primary text-lg", children: "Start your 14-day free trial" })] }), _jsx("section", { className: "grid md:grid-cols-3 gap-6", children: [
                            { title: 'Real-time sync', desc: 'All caregivers see updates instantly.' },
                            { title: 'PDF reports', desc: 'Branded summaries for pediatrician visits.' },
                            { title: 'CSV export', desc: 'Download all your data at any time.' },
                            { title: 'Vaccine tracking', desc: 'CDC schedule with due/overdue status.' },
                            { title: 'Privacy first', desc: 'Your data stays on your subdomain, isolated.' },
                            { title: 'PWA ready', desc: 'Install on your phone like a native app.' },
                        ].map(f => (_jsxs("div", { className: "card", children: [_jsx("h3", { className: "font-semibold text-stone-700", children: f.title }), _jsx("p", { className: "text-sm text-stone-500 mt-1", children: f.desc })] }, f.title))) }), _jsxs("section", { className: "text-center space-y-6", children: [_jsx("h2", { className: "text-3xl font-bold text-stone-800", children: "Simple pricing" }), _jsxs("div", { className: "card max-w-sm mx-auto", children: [_jsxs("p", { className: "text-4xl font-bold text-brand-600", children: ["$8", _jsx("span", { className: "text-lg text-stone-500 font-normal", children: "/mo" })] }), _jsx("p", { className: "text-sm text-stone-500 mt-1", children: "or $77/yr (~20% savings)" }), _jsxs("ul", { className: "text-sm text-stone-600 space-y-2 mt-4 text-left", children: [_jsx("li", { children: "\u2713 Unlimited babies & caregivers" }), _jsx("li", { children: "\u2713 All tracking features" }), _jsx("li", { children: "\u2713 Automatic SSL & backups" }), _jsx("li", { children: "\u2713 Platform-managed email & sign-in" }), _jsx("li", { children: "\u2713 Private subdomain" })] }), _jsx("button", { onClick: () => navigate('/signup'), className: "btn-primary w-full mt-6", children: "Start free trial" })] })] })] })] }));
}
